name: Migrating Jenkin-GitHub Action

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-scan: 
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      # Step 1: Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the application
      - name: Build with Maven
        run: mvn -B clean package

      # Step 5 Run SonarQube scan
      - name: Build and analyze with SonarQube
        run: mvn sonar:sonar \
              -Dsonar.projectKey=banita1985_Capstone-GitHubAction \
              -Dsonar.organization=banita1985 \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN
              
      # Step 6 List and Upload the artifacts
      - name: List target directory
        run: ls -l target/

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: githubaction-jar
          path: target/*.jar
        


    
